-- NonFap 2026 - esquema, RLS y Storage
-- Ejecutar una sola vez en Supabase > SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null,
  avatar_url text,
  cover_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.falls (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  fall_day smallint not null check (fall_day between 1 and 30),
  reason text not null check (char_length(reason) between 1 and 300),
  link text,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists cover_url text;

alter table public.profiles enable row level security;
alter table public.falls enable row level security;

-- Ranking y memorial públicos.
drop policy if exists "profiles public read" on public.profiles;
create policy "profiles public read" on public.profiles for select using (true);

drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "falls public read" on public.falls;
create policy "falls public read" on public.falls for select using (true);

drop policy if exists "falls own insert" on public.falls;
create policy "falls own insert" on public.falls for insert to authenticated with check (auth.uid() = user_id);

-- Crea el perfil automáticamente cuando el script inicial crea un usuario.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Bucket público para avatares. Las fotos son públicas, las escrituras no.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 2097152, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "avatar public read" on storage.objects;
create policy "avatar public read" on storage.objects for select using (bucket_id = 'avatars');

drop policy if exists "avatar own insert" on storage.objects;
create policy "avatar own insert" on storage.objects for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatar own delete" on storage.objects;
create policy "avatar own delete" on storage.objects for delete to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);


-- Bucket publico para portadas. Soporta GIF y mantiene permisos por usuario.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('covers', 'covers', true, 10485760, array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "cover public read" on storage.objects;
create policy "cover public read" on storage.objects for select using (bucket_id = 'covers');

drop policy if exists "cover own insert" on storage.objects;
create policy "cover own insert" on storage.objects for insert to authenticated
with check (bucket_id = 'covers' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "cover own delete" on storage.objects;
create policy "cover own delete" on storage.objects for delete to authenticated
using (bucket_id = 'covers' and (storage.foldername(name))[1] = auth.uid()::text);

-- Agrandar MB para Portada.
update storage.buckets
set file_size_limit = 10485760
where id = 'covers';