-- NonFap 2026 - esquema, RLS y Storage
-- Ejecutar una sola vez en Supabase > SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null,
  avatar_url text,
  cover_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.falls (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  fall_day smallint not null check (fall_day between 1 and 30),
  reason text not null check (char_length(reason) between 1 and 300),
  link text,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists cover_url text;

alter table public.profiles enable row level security;
alter table public.falls enable row level security;

-- Ranking y memorial públicos.
drop policy if exists "profiles public read" on public.profiles;
create policy "profiles public read" on public.profiles for select using (true);

drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "falls public read" on public.falls;
create policy "falls public read" on public.falls for select using (true);

drop policy if exists "falls own insert" on public.falls;
create policy "falls own insert" on public.falls for insert to authenticated with check (auth.uid() = user_id);

-- Crea el perfil automáticamente cuando el script inicial crea un usuario.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Bucket público para avatares. Las fotos son públicas, las escrituras no.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 2097152, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "avatar public read" on storage.objects;
create policy "avatar public read" on storage.objects for select using (bucket_id = 'avatars');

drop policy if exists "avatar own insert" on storage.objects;
create policy "avatar own insert" on storage.objects for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatar own delete" on storage.objects;
create policy "avatar own delete" on storage.objects for delete to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);


-- Bucket publico para portadas. Soporta GIF y mantiene permisos por usuario.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('covers', 'covers', true, 10485760, array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "cover public read" on storage.objects;
create policy "cover public read" on storage.objects for select using (bucket_id = 'covers');

drop policy if exists "cover own insert" on storage.objects;
create policy "cover own insert" on storage.objects for insert to authenticated
with check (bucket_id = 'covers' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "cover own delete" on storage.objects;
create policy "cover own delete" on storage.objects for delete to authenticated
using (bucket_id = 'covers' and (storage.foldername(name))[1] = auth.uid()::text);

-- Agrandar MB para Portada.
update storage.buckets
set file_size_limit = 10485760
where id = 'covers';

-- =========================================================
-- Tarea 1: Radio Lactea - comentarios, likes y ranking diario
-- =========================================================
create table if not exists public.radio_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 250),
  message_date date not null default ((now() at time zone 'America/Argentina/Buenos_Aires')::date),
  created_at timestamptz not null default now()
);

create table if not exists public.radio_message_likes (
  message_id bigint not null references public.radio_messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (message_id, user_id)
);

create index if not exists radio_messages_date_created_idx on public.radio_messages (message_date desc, created_at desc);
create index if not exists radio_message_likes_message_idx on public.radio_message_likes (message_id);

alter table public.radio_messages enable row level security;
alter table public.radio_message_likes enable row level security;

-- No exponer user_id: Radio Lactea es anonima y se lee por RPC get_radio_feed().
drop policy if exists "radio messages public read" on public.radio_messages;
drop policy if exists "radio messages own read" on public.radio_messages;
create policy "radio messages own read" on public.radio_messages for select to authenticated
using (auth.uid() = user_id);

-- La insercion se hace por RPC para que la fecha sea server-owned.
drop policy if exists "radio messages own insert" on public.radio_messages;

drop policy if exists "radio messages own delete" on public.radio_messages;
create policy "radio messages own delete" on public.radio_messages for delete to authenticated
using (auth.uid() = user_id);

-- No exponer quien likeo que: los conteos salen por RPC anonima.
drop policy if exists "radio likes public read" on public.radio_message_likes;
drop policy if exists "radio likes own read" on public.radio_message_likes;
create policy "radio likes own read" on public.radio_message_likes for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "radio likes own insert" on public.radio_message_likes;
create policy "radio likes own insert" on public.radio_message_likes for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "radio likes own delete" on public.radio_message_likes;
create policy "radio likes own delete" on public.radio_message_likes for delete to authenticated
using (auth.uid() = user_id);

-- =========================================================
-- Tarea 2: check-in diario, racha y puntos privados
-- =========================================================
create table if not exists public.daily_checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  checkin_date date not null default ((now() at time zone 'America/Argentina/Buenos_Aires')::date),
  challenge_day smallint not null check (challenge_day between 1 and 30),
  created_at timestamptz not null default now(),
  unique (user_id, checkin_date)
);

create index if not exists daily_checkins_user_date_idx on public.daily_checkins (user_id, checkin_date);

alter table public.daily_checkins enable row level security;

drop policy if exists "daily checkins own read" on public.daily_checkins;
create policy "daily checkins own read" on public.daily_checkins for select to authenticated
using (auth.uid() = user_id);

-- La insercion se hace por RPC para que fecha y challenge_day sean server-owned.
drop policy if exists "daily checkins own insert" on public.daily_checkins;

-- RPC server-owned: evita que el navegador falsifique fechas de Radio Lactea.
create or replace function public.create_radio_message(p_body text)
returns public.radio_messages
language plpgsql
security definer
set search_path = public
as $$
declare
  v_body text := btrim(coalesce(p_body, ''));
  v_message public.radio_messages;
begin
  if auth.uid() is null then
    raise exception 'Usuario no autenticado';
  end if;

  if char_length(v_body) < 1 or char_length(v_body) > 250 then
    raise exception 'El mensaje debe tener entre 1 y 250 caracteres';
  end if;

  insert into public.radio_messages (user_id, body, message_date)
  values (auth.uid(), v_body, (now() at time zone 'America/Argentina/Buenos_Aires')::date)
  returning * into v_message;

  return v_message;
end;
$$;

revoke execute on function public.create_radio_message(text) from public, anon;
grant execute on function public.create_radio_message(text) to authenticated;

-- Feed anonimo: devuelve mensajes y conteos sin user_id ni identidad del autor.
create or replace function public.get_radio_feed(p_limit integer default 200)
returns table (
  id bigint,
  body text,
  message_date date,
  created_at timestamptz,
  like_count integer,
  liked_by_me boolean,
  daily_rank bigint
)
language sql
stable
security definer
set search_path = public
as $$
with latest_messages as (
  select m.id, m.body, m.message_date, m.created_at
  from public.radio_messages m
  order by m.created_at desc
  limit least(greatest(coalesce(p_limit, 200), 1), 200)
),
today_messages as (
  select m.id, m.body, m.message_date, m.created_at
  from public.radio_messages m
  where m.message_date = (now() at time zone 'America/Argentina/Buenos_Aires')::date
),
visible_messages as (
  select * from latest_messages
  union
  select * from today_messages
),
today_like_counts as (
  select tm.id, count(l.user_id)::integer as like_count
  from today_messages tm
  left join public.radio_message_likes l on l.message_id = tm.id
  group by tm.id
),
ranked_today as (
  select tm.id, row_number() over (order by tlc.like_count desc, tm.created_at asc, tm.id asc) as daily_rank
  from today_messages tm
  join today_like_counts tlc on tlc.id = tm.id
  where tlc.like_count > 0
),
visible_like_counts as (
  select vm.id, count(l.user_id)::integer as like_count
  from visible_messages vm
  left join public.radio_message_likes l on l.message_id = vm.id
  group by vm.id
)
select
  vm.id,
  vm.body,
  vm.message_date,
  vm.created_at,
  vlc.like_count,
  exists (
    select 1
    from public.radio_message_likes my_like
    where my_like.message_id = vm.id and my_like.user_id = auth.uid()
  ) as liked_by_me,
  rt.daily_rank
from visible_messages vm
join visible_like_counts vlc on vlc.id = vm.id
left join ranked_today rt on rt.id = vm.id
order by vm.created_at desc;
$$;

revoke execute on function public.get_radio_feed(integer) from public, anon, authenticated;
grant execute on function public.get_radio_feed(integer) to anon, authenticated;

-- RPC server-owned: evita backfill o manipulacion del challenge_day desde el navegador.
create or replace function public.create_daily_checkin()
returns public.daily_checkins
language plpgsql
security definer
set search_path = public
as $$
declare
  v_today date := (now() at time zone 'America/Argentina/Buenos_Aires')::date;
  v_challenge_day smallint;
  v_checkin public.daily_checkins;
begin
  if auth.uid() is null then
    raise exception 'Usuario no autenticado';
  end if;

  if v_today < date '2026-09-01' or v_today > date '2026-09-30' then
    raise exception 'El check-in solo cuenta durante septiembre 2026';
  end if;

  if exists (select 1 from public.falls where user_id = auth.uid()) then
    raise exception 'Los soldados caidos no pueden sumar check-in diario';
  end if;

  v_challenge_day := (v_today - date '2026-09-01' + 1)::smallint;

  insert into public.daily_checkins (user_id, checkin_date, challenge_day)
  values (auth.uid(), v_today, v_challenge_day)
  returning * into v_checkin;

  return v_checkin;
end;
$$;

revoke execute on function public.create_daily_checkin() from public, anon;
grant execute on function public.create_daily_checkin() to authenticated;

-- Devuelve solo los puntos del usuario autenticado. No expone ranking publico de puntos.
create or replace function public.get_my_score()
returns table (
  checkin_points integer,
  checkin_streak integer,
  radio_points integer,
  total_points integer
)
language sql
stable
security invoker
set search_path = public
as $$
with my_checkins as (
  select checkin_date
  from public.daily_checkins
  where user_id = auth.uid()
),
checkin_count as (
  select count(*)::integer as total from my_checkins
),
streak_groups as (
  select checkin_date, checkin_date - (row_number() over (order by checkin_date))::integer as grp
  from my_checkins
),
streak_lengths as (
  select count(*)::integer as len
  from streak_groups
  group by grp
),
streak_score as (
  select coalesce(max(len), 0)::integer as longest_streak
  from streak_lengths
),
radio_like_counts as (
  select m.id, m.user_id, m.message_date, m.created_at, count(l.user_id)::integer as like_count
  from public.radio_messages m
  left join public.radio_message_likes l on l.message_id = m.id
  group by m.id, m.user_id, m.message_date, m.created_at
),
radio_winners as (
  select *, row_number() over (partition by message_date order by like_count desc, created_at asc, id asc) as daily_rank
  from radio_like_counts
  where like_count > 0
),
radio_score as (
  select (count(*) * 10)::integer as total
  from radio_winners
  where daily_rank = 1 and user_id = auth.uid()
)
select
  (cc.total * 5)
    + case when ss.longest_streak >= 5 then 20 else 0 end
    + case when ss.longest_streak >= 10 then 50 else 0 end
    + case when ss.longest_streak >= 20 then 100 else 0 end as checkin_points,
  ss.longest_streak as checkin_streak,
  rs.total as radio_points,
  ((cc.total * 5)
    + case when ss.longest_streak >= 5 then 20 else 0 end
    + case when ss.longest_streak >= 10 then 50 else 0 end
    + case when ss.longest_streak >= 20 then 100 else 0 end
    + rs.total)::integer as total_points
from checkin_count cc
cross join streak_score ss
cross join radio_score rs;
$$;

revoke execute on function public.get_my_score() from public, anon;
grant execute on function public.get_my_score() to authenticated;

-- Devuelve puntos publicos por soldado para ordenar el ranking y mostrar perfiles.
drop function if exists public.get_public_scores();
create or replace function public.get_public_scores()
returns table (
  user_id uuid,
  total_points integer
)
language sql
stable
security definer
set search_path = public
as $$
with users as (
  select id as user_id from public.profiles
),
user_checkins as (
  select u.user_id, dc.checkin_date
  from users u
  left join public.daily_checkins dc on dc.user_id = u.user_id
),
checkin_count as (
  select user_id, count(checkin_date)::integer as total
  from user_checkins
  group by user_id
),
streak_groups as (
  select user_id, checkin_date, checkin_date - (row_number() over (partition by user_id order by checkin_date))::integer as grp
  from user_checkins
  where checkin_date is not null
),
streak_lengths as (
  select user_id, count(*)::integer as len
  from streak_groups
  group by user_id, grp
),
streak_score as (
  select u.user_id, coalesce(max(sl.len), 0)::integer as longest_streak
  from users u
  left join streak_lengths sl on sl.user_id = u.user_id
  group by u.user_id
),
radio_like_counts as (
  select m.id, m.user_id, m.message_date, m.created_at, count(l.user_id)::integer as like_count
  from public.radio_messages m
  left join public.radio_message_likes l on l.message_id = m.id
  group by m.id, m.user_id, m.message_date, m.created_at
),
radio_winners as (
  select *, row_number() over (partition by message_date order by like_count desc, created_at asc, id asc) as daily_rank
  from radio_like_counts
  where like_count > 0
),
radio_score as (
  select u.user_id, (count(rw.id) filter (where rw.daily_rank = 1) * 10)::integer as total
  from users u
  left join radio_winners rw on rw.user_id = u.user_id
  group by u.user_id
)
select
  u.user_id,
  ((cc.total * 5)
    + case when ss.longest_streak >= 5 then 20 else 0 end
    + case when ss.longest_streak >= 10 then 50 else 0 end
    + case when ss.longest_streak >= 20 then 100 else 0 end
    + rs.total)::integer as total_points
from users u
join checkin_count cc on cc.user_id = u.user_id
join streak_score ss on ss.user_id = u.user_id
join radio_score rs on rs.user_id = u.user_id
order by total_points desc, u.user_id;
$$;

revoke execute on function public.get_public_scores() from public;
grant execute on function public.get_public_scores() to anon, authenticated;

-- =========================================================
-- Tarea 3: insignias y fueguito
-- =========================================================
-- No requiere columnas nuevas: la insignia se calcula desde falls + fecha del reto,
-- y el fueguito se calcula desde daily_checkins.
